### ISSUE TITLE
rpm_checksum and deb_checksum are too generic

### ISSUE THREAD

**Issue by pdehlke** [AustinCloudGuru/ansible-role-splunk-forwarder#2]
It'd be cool if these variables more closely matched the role. Maybe splunk_rpm_checksum and splunk_deb_checksum.

I've seen other roles with a variable called rpm_checksum; this makes it really hard to include multiple roles in the same playbook :)

Thanks

**Comment by AustinCloudGuru** [comment]
Thanks for pointing it out!
