### ISSUE TITLE
Don't run User/Group tasks for RPM

### ISSUE THREAD

**Issue by sroughto** [AustinCloudGuru/ansible-role-splunk-forwarder#5]
The Splunk Forwarder RPM automatically creates the splunk user and group, whose ids might differ from the playbook variables. It might be helpful to remove the uid/gid from the user and group tasks, or run these tasks only for non-rpm packages (e.g., when: ansible_os_family != "RedHat").

Nice work on this role.

**Comment by bschonec** [comment]
Seconded....

**Comment by AustinCloudGuru** [comment]
Sorry I didn't back to this earlier.  If the user exists, the splunk RPM will use that user.  The reason that I include it in this role is so that you can choose which UID/GID to give it so that it is the same across all instances and not just choosing the next available.
