### ISSUE TITLE
Support Multiple sourcetypes

### ISSUE THREAD

**Issue by sroughto** [austincloudguru/ansible-role-splunk-forwarder#6]
The role can setup forwarding for one sourcetype (in the example, nginx). It would be helpful if the sourcetype/logs tasks could operate on an array of tuples (sourcetype, logfile, index), for example, to enable logging different types of files (such as nginx logs and /var/log/messages).

**Comment by rayrayrayraydog** [comment]
I would find this useful as well.

**Comment by schadom** [comment]
+1
